version: "3.8"

networks:
  shared-network:
    external: true

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: event-service-client
    depends_on:
      - server
    ports:
      - "6001:6001"
    networks:
      - shared-network
    # Optionally, set environment variables or volumes if needed

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: event-service-server
    ports:
      - "50051:50051"
    networks:
      - shared-network
    # Optionally, set environment variables or volumes if needed
